[package]
name = "uurlog-paymo"
version = "0.1.0"
authors = ["Maarten de Vries <maarten@de-vri.es>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10.6", features = ["json"] }
serde = { version = "1.0.111", features = ["derive"] }
structopt = "0.3.14"
tokio = { version = "0.2.21", features = ["macros", "rt-core", "time"] }
uurlog = { git = "https://github.com/de-vri-es/uurlog" }
urlencoding = "1.0.0"
